#!/bin/bash

# Essentials
if [[ $(command -v eza) ]]; then
    alias ll='eza -hal --icons=auto'
    alias la='eza -a'
    alias show='eza -hal $(fzf-ls)'
    alias tree="eza -T"
else
    alias ll='ls -la'
    alias la='ls -a'
    alias show='ls -la $(fzf-ls)'
fi
alias v='nvim'
alias c='cd $(fzf-cd)'
alias td='tmux-dev'
alias wd='source $HOME/bin/wez-dev'

alias pp='pbpaste'
alias pc='pbcopy'

# Typos
alias claer='clear'
alias clera='clear'
alias :wq='echo "Wrong pane"'
alias :w='echo "Wrong pane"'
alias :q='echo "Wrong pane"'

# Git
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'

alias gl="git log \
    --graph \
    --stat \
    --stat-graph-width=15 \
    --pretty='%Cred%h%Creset -%C(auto)%d%Creset %C(bold)%C(#f2cdcd)%s%Creset %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias gc='fzf-git-checkout'
alias gpf='gpush --force-with-lease'
alias gf='git commit --fixup=$(fzf-git-commits)'
alias cpr='gh-create-pr'

alias kitty-update='curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin'

# sqlize, but use clipboard as in/out
alias pbsqlize='pbpaste | sqlize | pbcopy'
