#!/bin/bash

# Essentials
if [[ $(command -v exa) ]]; then
    alias ll='exa -hal'
    alias la='exa -a'
    alias show='exa -hal $(fzf-ls)'
else
    alias ll='ls -la'
    alias la='ls -a'
    alias show='ls -la $(fzf-ls)'
fi
alias v='nvim'
alias claer='clear'
alias c='cd $(fzf-cd)'

# Git
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'

alias gl="git log \
    --graph \
    --stat \
    --stat-graph-width=15 \
    --pretty='%Cred%h%Creset -%C(auto)%d%Creset %C(bold)%s%Creset %Cgreen(%ar) %C(bold blue)<%an>%Creset'"
alias gc='fzf-git-checkout'
alias gpf='gpush --force-with-lease'
alias gf='git commit --fixup=$(fzf-git-commits)'

alias kitty-update='curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin'
