#!/bin/sh
function git_config {
    local cmd="git config --global"
    runcmd "$cmd" $@
}

function setup_git {
    # aliases
    git_config alias.update "fetch origin master:master"
    git_config alias.cleanup "! zsh -i -c 'git branch --merged master | grep -v master | xargs git branch -d'"
    git_config alias.rockstars "shortlog -s -n --no-merges"
    git_config alias.count-lines "! git log --author=\"\${1:-Alexander Garcia}\" --pretty=tformat: --numstat | grep -v '.lock$' | awk '{ add += \$1; subs += \$2; loc += \$1 - \$2 } END { printf \"added lines: %s, removed lines: %s, total lines: %s\n\", add, subs, loc }' #"

    # settings
    git_config core.pager "fzf-delta"
    git_config push.autoSetupRemove "true"
    git_config fetch.prune "true"
    git_config pull.rebase "true"

    # colors
    git_config diff.colorMoved "zebra"
    # delta
    git_config delta.features "decorations"
    git_config delta.file-decoration-style "brightgreen bold ol"
    git_config delta.file-style "brightgreen auto"
    git_config delta.hunk-header-style "omit"
    git_config delta.line-numbers "true"
    # tokyonight-moon theme
    git_config delta.minus-style                   'syntax "#3a273a"'
    git_config delta.minus-non-emph-style          'syntax "#3a273a"'
    git_config delta.minus-emph-style              '"#1b1d2b" "#c53b53"'
    git_config delta.minus-empty-line-marker-style 'syntax "#3a273a"'
    git_config delta.plus-style                    'syntax "#273849"'
    git_config delta.plus-non-emph-style           'syntax "#273849"'
    git_config delta.plus-emph-style               '"#1b1d2b" "#89b4fa"'
    git_config delta.plus-empty-line-marker-style  'syntax "#273849"'
    # git log --graph (catppuccin colors: https://github.com/catppuccin/catppuccin)
    git_config log.graphColors '"#d20f39","#8839ef","#179299","#df8e1d","#40a02b","#fe640b","#7287fd"'

    # `git-absorb`
    git_config absorb.maxStack 20
}

setup_git
