export LANG=en_US.UTF-8

export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

[ -d /opt/homebrew ] && eval "$(/opt/homebrew/bin/brew shellenv)"
