export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Brew setup
if [ -d /opt/homebrew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    # Autocomplete from installed apps
    FPATH="$(brew --prefix)/share/zsh/site-functions:$FPATH"
    # Let gcc play with brew
    export LDFLAGS="-L$(brew --prefix)/opt/zlib/lib -L$(brew --prefix)/opt/bzip2/lib -L$(brew --prefix openssl)/lib"
    export CPPFLAGS="-I$(brew --prefix)/opt/zlib/include -I$(brew --prefix)/opt/bzip2/include -I$(brew --prefix openssl)/include"
    export CFLAGS="-I$(brew --prefix openssl)/include \
        -I$(brew --prefix bzip2)/include \
        -I$(brew --prefix readline)/include \
        -I$(xcrun --show-sdk-path)/usr/include"
fi
