# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="quarter-life"
#
# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"
# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="false"
unsetopt correct_all

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/

if [[ -f ~/.custom ]]; then
    source ~/.custom
fi

# OMZ config
plugins=(
    git
    ripgrep
    zsh-interactive-cd
    zsh-vi-mode
)

# vi mode
# NOTE: edit command in $EDITOR happens from zsh-vi-mode with `vv`
# make sure fzf keybindings still apply
zvm_after_init() {
    [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
    [ -f ~/.functions ] && source ~/.functions
    source "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
}
# Do vim surround on the command line
export ZVM_VI_SURROUND_BINDKEY='classic'

source $ZSH/oh-my-zsh.sh

# Brew
if [[ -d /opt/homebrew ]]; then
    eval $(/opt/homebrew/bin/brew shellenv)
    # Autocomplete
    if type brew &>/dev/null; then
      FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
    fi
    # Let gcc play with brew
    export LDFLAGS="-L$(brew --prefix)/opt/zlib/lib -L$(brew --prefix)/opt/bzip2/lib -L$(brew --prefix openssl)/lib"
    export CPPFLAGS="-I$(brew --prefix)/opt/zlib/include -I$(brew --prefix)/opt/bzip2/include -I$(brew --prefix openssl)/include"
    export CFLAGS="-I$(brew --prefix openssl)/include \
        -I$(brew --prefix bzip2)/include \
        -I$(brew --prefix readline)/include \
        -I$(xcrun --show-sdk-path)/usr/include"
fi

# User configuration

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

autoload -Uz compinit && compinit # completion
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
autoload -U add-zsh-hook # hooks

# syntax highlights, must run after compinit - https://github.com/zsh-users/zsh-syntax-highlighting?tab=readme-ov-file#faq
# https://github.com/catppuccin/zsh-syntax-highlighting
syntax_highlights="$HOME/.zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh"
if [[ -f $syntax_highlights ]]; then
    source "$syntax_highlights"
fi
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# use bat for manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export BAT_THEME="Catppuccin-mocha"

# FZF things
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd -tf'
# Basic global opts
export FZF_DEFAULT_OPTS="--height 60% \
    --border=none \
    --info=inline-right \
    --scrollbar=▏▕ \
    --reverse \
    --multi \
    --bind 'ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down' \
    --bind 'ctrl-h:toggle-preview'\
    --bind 'ctrl-y:jump-accept'"
# catppuccin "mocha" color scheme -- https://github.com/catppuccin/catppuccin#-palette
export FZF_COLOR_OPTS="--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
    --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
    --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
    --color=preview-border:#45475a,preview-scrollbar:#45475a \
    --color=selected-fg:#fab387"
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS $FZF_COLOR_OPTS"

# Python
if [[ -d "$HOME/.pyenv" ]]; then
    eval "$(pyenv init -)"
fi
if [[ -d "$HOME/.rye" ]]; then
    source "$HOME/.rye/env"
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
if [[ -d "$NVM_DIR" ]]; then
    nvm_default="$(nvm which default)"
    export DEFAULT_NODE_VERSION="$("$nvm_default" --version)"
    # Automatically use nvm version specified in .nvmrc (if any)
    # Intentionally not very flexible to avoid calling nvm every time we change directory
    function load-nvmrc {
        local nvmrc_path=".nvmrc"

        if [ -f "$nvmrc_path" ]; then
            local nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")

            if [ "$nvmrc_node_version" = "N/A" ]; then
                nvm install
            elif [ "$nvmrc_node_version" != $(nvm version) ]; then
                nvm use
            fi
        fi
    }

    # Load nvmrc if I'm switching branches
    branching=false
    function nvm-git-branch {
        local cmd="$1"
        if [[ $cmd && $cmd =~ "^git (checkout|branch)" && ! $braching ]]; then
            branching=true
        elif [[ $branching ]]; then
            load-nvmrc
            branching=false
        fi
    }

    add-zsh-hook preexec nvm-git-branch
    add-zsh-hook precmd nvm-git-branch
    add-zsh-hook chpwd load-nvmrc
fi
# NVM end

# Lua ls
export PATH="$PATH:$HOME/lua-language-server/bin"
alias luamake=$HOME/lua-language-server/3rd/luamake/luamake

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
[ -s "$HOME/.aliases" ] && source ~/.aliases
[ -s "$HOME/.functions" ] && source ~/.functions
# rust
export PATH="$HOME/.cargo/bin:$PATH"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# wez
export PATH="$PATH:/Applications/WezTerm.app/Contents/MacOS"

# go
export GOROOT="$(brew --prefix)/Cellar/go/1.20.3/libexec"
export PATH="$PATH:$GOROOT/bin"

# flutter
export PATH="$HOME/devel/flutter/bin:$PATH"
